### ISSUE TITLE
ignores.suspend not filtering UndispatchedCoroutine

### ISSUE THREAD

**Issue by anderssv** [newrelic/newrelic-java-kotlin-coroutines#16]
I am not absolutely this should work, but it seems I can't ignore suspend traces for example for `Custom/WrappedSuspend/UndispatchedCoroutine` .

I have added the following to newrelic.yml:

```
  Coroutines:
    ignores:
      continuations: jetty-call-handler
      suspends: UndispatchedCoroutine,jetty-call-handler
      dispatched: io.ktor.utils.io.jvm.javaio.OutputAdapter$loop$1$loop$1,io.ktor.utils.io.ByteBufferChannel$writeSuspend$1
```

The filtering on dispatched works, but for suspends it does not seem to work. Am I on the right track here?
